version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: maintenance17/foodgram_backend
    volumes:
      - static:/static
      - media:/app/media/
    env_file: .env
    depends_on:
      - db

  frontend:
    image: maintenance17/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    image: maintenance17/foodgram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/app/media/
