# Generated by Django 4.2.4 on 2023-08-17 22:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("foodgram", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Follow",
        ),
    ]
