# Generated by Django 4.2.4 on 2023-08-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0003_rename_description_recipe_text_alter_favorite_recipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingridient',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
